# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8
  host: android-survey.csmlcxz0rkff.us-east-1.rds.amazonaws.com
  database: android_survey
  username: root
  password: android-survey-root

development:
  <<: *default

test:
  <<: *default
  
sandbox:
  <<: *default

integration:
  <<: *default

production:
  <<: *default